/**********************************************************************************************************************
DEVELOPER: JOHN O. UMUKORO
DATE CREATED: 2025-04-21
CODE VERSION: 1.0
DESCRIPTION: THIS CODE PROVIDES INFORMATION ABOUT CONSUMER COMPLAINTS
PROJECT SCOPE:  1: LOAD CONSUMER COMPLAINTS AND DATA AND CORRESPONDING DATA DICTIONARY TO DATABASE 
				2: CREATE SQL QUERIES TO GENERATE METRICS AND PARAMETERIZED PROCEDURES FOR ANALYSIS ANS SUMMARY REPORT
				3: PRODUCE A BUSINESS INTELLIGENCE REPORT
**********************************************************************************************************************/


SELECT * FROM CONSUMERCOMPLAINTSDATADICTIONARY
SELECT * FROM CONSUMERCOMPLAINTS

--1 MONTHLY COMPLAINT VOLUME TREND
SELECT 
    UPPER(LEFT(DATENAME(MONTH, [DATE SUBMITTED]), 3)) + '-' + CAST(YEAR([DATE SUBMITTED]) AS VARCHAR) AS MONTH,
    COUNT(*) AS TOTALCOMPLAINTS
FROM DBO.CONSUMERCOMPLAINTS
GROUP BY 
    YEAR([DATE SUBMITTED]),
    MONTH([DATE SUBMITTED]),
    DATENAME(MONTH, [DATE SUBMITTED])
ORDER BY YEAR([DATE SUBMITTED]), MONTH([DATE SUBMITTED]);



--2 TOP 10 PRODUCTS BY COMPLAINT VOLUME
SELECT 
    PRODUCT, 
    COUNT(*) AS COMPLAINTCOUNT
FROM DBO.CONSUMERCOMPLAINTS
GROUP BY PRODUCT
ORDER BY COMPLAINTCOUNT DESC;


--3  COMPLAINT DISTRIBUTION BY STATE
SELECT 
    STATE, 
    COUNT(*) AS COMPLAINTS
FROM DBO.CONSUMERCOMPLAINTS
GROUP BY STATE
ORDER BY COMPLAINTS DESC;

--4 MOST COMMON ISSUES PER PRODUCT
SELECT 
    PRODUCT, 
    ISSUE, 
    COUNT(*) AS ISSUECOUNT
FROM DBO.CONSUMERCOMPLAINTS
GROUP BY PRODUCT, ISSUE
ORDER BY PRODUCT, ISSUECOUNT DESC;

--5 TIMELY RESPONSE RATE BY PRODUCT
SELECT 
    PRODUCT, 
    COUNT(*) AS TOTAL,
    SUM(CASE WHEN [TIMELY RESPONSE?] = 'YES' THEN 1 ELSE 0 END) AS TIMELYRESPONSES,
    CAST(100.0 * SUM(CASE WHEN [TIMELY RESPONSE?] = 'YES' THEN 1 ELSE 0 END) / COUNT(*) AS DECIMAL(5,2)) AS TIMELYRATEPERCENT
FROM DBO.CONSUMERCOMPLAINTS
GROUP BY PRODUCT
ORDER BY TIMELYRATEPERCENT DESC;

--6 COMPLAINTS WITH NO PUBLIC COMPANY RESPONSE
SELECT 
    COUNT(*) AS NOPUBLICRESPONSECOUNT
FROM DBO.CONSUMERCOMPLAINTS
WHERE [COMPANY PUBLIC RESPONSE] IS NULL;

--7 SUB-PRODUCTS DRIVING MOST COMPLAINTS
SELECT 
    [SUB-PRODUCT], 
    COUNT(*) AS COMPLAINTCOUNT
FROM DBO.CONSUMERCOMPLAINTS
GROUP BY [SUB-PRODUCT]
ORDER BY COMPLAINTCOUNT DESC;

--8 COMPANY RESPONSE BEHAVIOR OVERVIEW
SELECT 
    [COMPANY RESPONSE TO CONSUMER], 
    COUNT(*) AS RESPONSECOUNT
FROM DBO.CONSUMERCOMPLAINTS
GROUP BY [COMPANY RESPONSE TO CONSUMER]
ORDER BY RESPONSECOUNT DESC;

--9 SUBMITTED METHOD BREAKDOWN
SELECT 
    [SUBMITTED VIA], 
    COUNT(*) AS SUBMISSIONCOUNT
FROM DBO.CONSUMERCOMPLAINTS
GROUP BY [SUBMITTED VIA]
ORDER BY SUBMISSIONCOUNT DESC;

-- PROCEDURE 1: MONTHLY COMPLAINT VOLUME (WITHIN DATE RANGE)
CREATE PROCEDURE SP_GETMONTHLYCOMPLAINTS
    @STARTDATE DATE,
    @ENDDATE DATE
AS
BEGIN
SELECT 
    UPPER(LEFT(DATENAME(MONTH, [DATE SUBMITTED]), 3)) + '-' + CAST(YEAR([DATE SUBMITTED]) AS VARCHAR) AS MONTH,
    COUNT(*) AS TOTALCOMPLAINTS
FROM DBO.CONSUMERCOMPLAINTS
GROUP BY 
    YEAR([DATE SUBMITTED]),
    MONTH([DATE SUBMITTED]),
    DATENAME(MONTH, [DATE SUBMITTED])
ORDER BY YEAR([DATE SUBMITTED]), MONTH([DATE SUBMITTED]);
END

-- PROCEDURE 2: COMPLAINT COUNT BY PRODUCT (WITHIN DATE RANGE)
CREATE PROCEDURE SP_GETCOMPLAINTSBYPRODUCT
    @STARTDATE DATE,
    @ENDDATE DATE
AS
BEGIN
SELECT 
    PRODUCT, 
    COUNT(*) AS COMPLAINTCOUNT
FROM DBO.CONSUMERCOMPLAINTS
GROUP BY PRODUCT
ORDER BY COMPLAINTCOUNT DESC;
END

--PROCEDURE 3: TIMELY RESPONSE RATE BY PRODUCT
CREATE PROCEDURE SP_TIMELYRESPONSEBYPRODUCT
    @STARTDATE DATE,
    @ENDDATE DATE
AS
BEGIN
SELECT 
    PRODUCT, 
    COUNT(*) AS TOTAL,
    SUM(CASE WHEN [TIMELY RESPONSE?] = 'YES' THEN 1 ELSE 0 END) AS TIMELYRESPONSES,
    CAST(100.0 * SUM(CASE WHEN [TIMELY RESPONSE?] = 'YES' THEN 1 ELSE 0 END) / COUNT(*) AS DECIMAL(5,2)) AS TIMELYRATEPERCENT
FROM DBO.CONSUMERCOMPLAINTS
GROUP BY PRODUCT
ORDER BY TIMELYRATEPERCENT DESC;
END

-- PROCEDURE 4: COMPLAINTS BY STATE (WITH DATES)
CREATE PROCEDURE SP_GETCOMPLAINTSBYSTATE
    @STARTDATE DATE,
    @ENDDATE DATE
AS
BEGIN
SELECT 
    STATE,
    COUNT(*) AS COMPLAINTCOUNT
FROM DBO.CONSUMERCOMPLAINTS
WHERE [DATE SUBMITTED] BETWEEN @STARTDATE AND @ENDDATE
GROUP BY STATE
ORDER BY COMPLAINTCOUNT DESC;
END


-- PROCEDURE 5: SUBMISSION METHOD BREAKDOWN
CREATE PROCEDURE SP_SUBMISSIONCHANNELBREAKDOWN
    @STARTDATE DATE,
    @ENDDATE DATE
AS
BEGIN
    SELECT 
        [SUBMITTED VIA],
        COUNT(*) AS TOTAL
    FROM DBO.CONSUMERCOMPLAINTS
    WHERE [DATE SUBMITTED] BETWEEN @STARTDATE AND @ENDDATE
    GROUP BY [SUBMITTED VIA]
    ORDER BY TOTAL DESC;
END


EXEC SP_GETMONTHLYCOMPLAINTS @STARTDATE = '2023-01-01', @ENDDATE = '2023-12-31';


