/**********************************************************************************************************************
DEVELOPER: JOHN O. UMUKORO
DATE CREATED: 2024-10-31
CODE VERSION: 1.0
DESCRIPTION: THIS CODE PROVIDES INFORMATION ABOUT CALIFORNIA HOSPITAL FACILITIES LISTING
PROJECT SCOPE:  1: LOAD HOSPITAL FACILITIES DATA TO DATABASE 
				2: CREATE SQL QUERIES TO GENERATE METRICS LIKE TOTAL COUNTS, NUMBER OF BEDS, NUMBER OF FACILITY TYPE, SHOW COUNTY MAPS FOR TOTAL NUMBER OF FACILITIES IN EACH COUNTY IN CALIFORNIA 
				3: PRODUCE A BUSINESS INTELLIGENCE REPORT SHOWING DIFFERENT KPIS
**********************************************************************************************************************/

-- CONFIRM DATA LOADED INTO DATABASE
SELECT *
FROM HOSPITALFACILITYLISTING

--TOTAL COUNT OF FACILITIES IN CALIFORNIA
SELECT 
COUNT (FACID) AS TOTAL_COUNT_OF_REGISTERED_FACILITIES_IN_CALIFORNIA
FROM HOSPITALFACILITYLISTING

--SAVE AS VIEW
CREATE VIEW VW_TOTAL_COUNT_OF_REGISTERED_FACILITIES_IN_CALIFORNIA AS
(
SELECT 
COUNT (FACID) AS TOTAL_COUNT_OF_REGISTERED_FACILITIES_IN_CALIFORNIA
FROM HOSPITALFACILITYLISTING
)

--TOTAL COUNTS OF FACILITIES BY FACILITY TYPE
SELECT FAC_TYPE_CODE,
COUNT (FACID) AS TOTAL_NUMBER_OF_FACILITIES_BY_TYPE
FROM HOSPITALFACILITYLISTING
GROUP BY FAC_TYPE_CODE
ORDER BY TOTAL_NUMBER_OF_FACILITIES DESC

--SAVE AS VIEW
CREATE VIEW VW_TOTAL_NUMBER_OF_FACILITIES_BY_TYPE AS
(
SELECT FAC_TYPE_CODE,
COUNT (FACID) AS TOTAL_NUMBER_OF_FACILITIES_BY_TYPE
FROM HOSPITALFACILITYLISTING
GROUP BY FAC_TYPE_CODE
--ORDER BY TOTAL_NUMBER_OF_FACILITIES DESC
)


--NUMBER OF BEDS
SELECT 
SUM(CAPACITY) AS NUMBER_OF_BEDS
FROM HOSPITALFACILITYLISTING

--SAVE AS VIEW
CREATE VIEW VW_NUMBER_OF_BEDS AS
(
SELECT 
SUM(CAPACITY) AS NUMBER_OF_BEDS
FROM HOSPITALFACILITYLISTING
)



--NUMBER OF FACILITY TYPE
SELECT 
COUNT(DISTINCT FAC_TYPE_CODE) AS NUMBER_OF_FACILITY_TYPE
FROM HOSPITALFACILITYLISTING

--SAVE AS VIEW
CREATE VIEW VW_NUMBER_OF_FACILITY_TYPE AS
(
SELECT 
COUNT(DISTINCT FAC_TYPE_CODE) AS NUMBER_OF_FACILITY_TYPE
FROM HOSPITALFACILITYLISTING
)


--TOTAL NUMBER OF FACILITIES IN EACH COUNTY
SELECT COUNTY_NAME,
COUNT (FACID) AS TOTAL_NUMBER_OF_FACILITIES_BY_COUNTY
FROM HOSPITALFACILITYLISTING
GROUP BY COUNTY_NAME
ORDER BY TOTAL_NUMBER_OF_FACILITIES_BY_COUNTY DESC

--SAVE AS VIEW
CREATE VIEW VW_TOTAL_NUMBER_OF_FACILITIES_BY_COUNTY AS
(
SELECT COUNTY_NAME,
COUNT (FACID) AS TOTAL_NUMBER_OF_FACILITIES_BY_COUNTY
FROM HOSPITALFACILITYLISTING
GROUP BY COUNTY_NAME
--ORDER BY TOTAL_NUMBER_OF_FACILITIES_BY_COUNTY DESC
)

--Available hospice care beds
SELECT FAC_TYPE_CODE,
COUNT(CAPACITY) AS NUMBER_OF_HOSPICE_BEDS
FROM HOSPITALFACILITYLISTING
WHERE FAC_TYPE_CODE='HOSPICE'
GROUP BY FAC_TYPE_CODE

--SAVE AS VIEW
CREATE VIEW VW_HOSPICE_BEDS AS
(
SELECT FAC_TYPE_CODE,
COUNT(CAPACITY) AS NUMBER_OF_HOSPICE_BEDS
FROM HOSPITALFACILITYLISTING
WHERE FAC_TYPE_CODE='HOSPICE'
GROUP BY FAC_TYPE_CODE
)

-- COUNT OF ACUTE BEDS BY FACILITY TYPE
SELECT FAC_TYPE_CODE,
COUNT(CAPACITY) AS COUNT_OF_ACUTE_BEDS_BY_FAC_TYPE
FROM HOSPITALFACILITYLISTING
WHERE FACNAME LIKE '%ACUTE%'
GROUP BY FAC_TYPE_CODE

--SAVE AS VIEW
CREATE VIEW VW_ACUTE_BEDS_BY_FAC_TYPE AS
(
SELECT FAC_TYPE_CODE,
COUNT(CAPACITY) AS COUNT_OF_ACUTE_BEDS_BY_FAC_TYPE
FROM HOSPITALFACILITYLISTING
WHERE FACNAME LIKE '%ACUTE%'
GROUP BY FAC_TYPE_CODE
)

--COUNT OF ACUTE BEDS
SELECT 
COUNT(CAPACITY) AS COUNT_OF_ACUTE_BEDS_BY_FAC_TYPE
FROM HOSPITALFACILITYLISTING
WHERE FACNAME LIKE '%ACUTE%'

--SAVE AS VIEW
CREATE VIEW VW_ACUTE_BEDS AS
(
SELECT 
COUNT(CAPACITY) AS COUNT_OF_ACUTE_BEDS
FROM HOSPITALFACILITYLISTING
WHERE FACNAME LIKE '%ACUTE%'
)
--CAN BE CERTIFIED ACUTE BEDS
SELECT 
COUNT(CAPACITY) AS CAN_BE_CERTIFIED_ACUTE_BEDS
FROM HOSPITALFACILITYLISTING
WHERE FACNAME LIKE '%ACUTE%'
and CAN_BE_CERTIFIED_FAC_TYPE='Y';

--SAVE AS VIEW
CREATE VIEW VW_CAN_BE_CERTIFIED_ACUTE_BEDS AS
(
SELECT 
COUNT(CAPACITY) AS CAN_BE_CERTIFIED_ACUTE_BEDS
FROM HOSPITALFACILITYLISTING
WHERE FACNAME LIKE '%ACUTE%'
and CAN_BE_CERTIFIED_FAC_TYPE='Y'
)

--STATUS COUNT OF facilities
SELECT 
COUNT(licensed_certified) AS [LICENSED ONLY]
FROM HOSPITALFACILITYLISTING
WHERE LICENSED_CERTIFIED ='LICENSED ONLY'

SELECT 
COUNT(licensed_certified) AS [LICENSED AND CERTIFIED]
FROM HOSPITALFACILITYLISTING
WHERE LICENSED_CERTIFIED ='LICENSED AND CERTIFIED'

SELECT 
COUNT(licensed_certified) AS [NOT LICENSED/NOT CERTIFIED]
FROM HOSPITALFACILITYLISTING
WHERE LICENSED_CERTIFIED ='NOT LICENSED/NOT CERTIFIED'

SELECT 
COUNT(licensed_certified) AS [CERTIFIED ONLY]
FROM HOSPITALFACILITYLISTING
WHERE LICENSED_CERTIFIED ='CERTIFIED ONLY'

SELECT 
COUNT(licensed_certified) AS STATUS
FROM HOSPITALFACILITYLISTING

--ALTERNATIVELY USING PIVOT TO SHOW STATUS COUNT
SELECT *
FROM
(
SELECT LICENSED_CERTIFIED,
COUNT(LICENSED_CERTIFIED) AS STATUS
FROM HOSPITALFACILITYLISTING
GROUP BY LICENSED_CERTIFIED
) SOURCETABLE
	PIVOT (SUM([STATUS])
	FOR [LICENSED_CERTIFIED] IN 
	([CERTIFIED ONLY],
	[LICENSED ONLY],
	[LICENSED AND CERTIFIED],
	[NOT LICENSED/NOT CERTIFIED])
	) STATUSPIVOT

--SAVE AS VIEW
CREATE VIEW VW_STATUS_COUNT AS
(
SELECT *
FROM
(
SELECT LICENSED_CERTIFIED,
COUNT(LICENSED_CERTIFIED) AS STATUS
FROM HOSPITALFACILITYLISTING
GROUP BY LICENSED_CERTIFIED
) SOURCETABLE
	PIVOT (SUM([STATUS])
	FOR [LICENSED_CERTIFIED] IN 
	([CERTIFIED ONLY],
	[LICENSED ONLY],
	[LICENSED AND CERTIFIED],
	[NOT LICENSED/NOT CERTIFIED])
	) STATUSPIVOT
	)

