
SELECT YEAR,SUBJECT,WINNER,
COUNT(YEAR) YEARS
FROM NOBLE
GROUP BY YEAR,SUBJECT,WINNER

SELECT *
FROM NOBLE

SELECT YEAR,SUBJECT,WINNER,
COUNT(YEAR) YEARS
FROM NOBLE
GROUP BY YEAR,SUBJECT,WINNER
HAVING COUNT(YEAR) > 1

--USING PIVOT: ITS USED TO CONVERT ROWS TO COLUMN
SELECT *
FROM
	(
	SELECT YEAR,SUBJECT,WINNER,
	COUNT(YEAR) YEARS
	FROM NOBLE
	GROUP BY YEAR,SUBJECT,WINNER
	) SOURCETABLE

PIVOT(SUM([YEARS])
FOR YEAR IN ([1960],[1961],[1962],[1963])
	) YEARPIVOT


	;WITH TABLE_A AS
	(
	SELECT 
	A.FIRST_NAME,
	A.MIDDLE_NAME,
	A.LAST_NAME,
	A.HIRE_DATE,
	A.SALARY,
	A.JOB_ID
FROM EMADECONSULTINGEMPLOYEE A
	),
	TABLE_B AS
	(
	SELECT B.JOB_ID,B.DESIGNATION
	FROM  EMADECONSULTINGJOB B
	),
	TABLE_C AS
	(
	SELECT *
	FROM EMADECONSULTINGDEPARTMENT C 
	),
	TABLE_D AS
	(
	SELECT *
	FROM EMADECONSULTINGLOCATION D
	),
	 FINAL AS
	(
	SELECT A.*,B.DESIGNATION
	FROM TABLE_A A
	INNER JOIN TABLE_B B ON A.JOB_ID=B.JOB_ID
	)
/**	UPDATE FINAL
	SET DESIGNATION='SENIOR MANAGER'
	WHERE DESIGNATION='MANAGER';
	**/
SELECT *
FROM FINAL